<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="{$robots}" n:ifset="$robots" />
    <title>{block #title}Redakční systém Upravuj{/block}
    </title>
    <link rel="stylesheet" href="{$basePath}/css/admin.css" type="text/css" media="screen, projection, tv" />
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" src="{$basePath}/js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript" src="{$basePath}/js/jfancybox/jquery.mousewheel-3.0.4.pack.js"></script>
    <link rel="stylesheet" type="text/css" href="{$basePath}/js/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
    <link rel="stylesheet" href="{$basePath}/js/jwysiwyg/jquery.wysiwyg.css" type="text/css" />
<script type="text/javascript" src="{$basePath}/js/jwysiwyg/jquery.wysiwyg.js"></script>
<script type="text/javascript" src="{$basePath}/js/datapicker/jquery-ui-1.8.6.custom.min.js"></script>
<script type="text/javascript" src="{$basePath}/js/datapicker/jquery.ui.datepicker-cs.js"></script>
<link rel="stylesheet" type="text/css" href="{$basePath}/js/smoothness/jquery-ui-1.8.6.custom.css" media="screen" />
<script type="text/javascript" src="{$basePath}/js/adds.js"></script>
  </head>
  <body>
    <div id="container">
      <div id="top">
      </div>
      <div id="menu">
        <div style="text-align: left">
          <ul id="nav">
            <li>
            <a href="{plink Default:}">
              <img src="{$baseUri}img/admin/go_home.png" height="50" width="50" alt="Domů"></a>
            <ul>
              <li>
              <a href="{plink Default:}">Domů</a>
              </li>
            </ul>
            <div class="clear">
            </div>
            </li>
            <li>
            <a href="javascript:self.history.back();">
              <img src="{$baseUri}img/admin/edit_undo.png" height="50" width="50" alt="Zpět"></a>
            <ul>
              <li>
              <a href="javascript:self.history.back();">Zpět</a>
              </li>
            </ul>
            <div class="clear">
            </div>
            </li>
            <li>
            <a href="javascript:self.history.forward();">
              <img src="{$baseUri}img/admin/edit_redo.png" height="50" width="50" alt="Vpřed"></a>
            <ul>
              <li>
              <a href="javascript:self.history.forward();">Vpřed</a>
              </li>
            </ul>
            <div class="clear">
            </div>
            </li>
            <li>
            <a href="{link Menu:}">
              <img src="{$baseUri}img/admin/fileview_split.png" height="50" width="50" alt="Menu"></a>
            <ul>
              <li>
              <a href="{link Menu:}">Menu</a>
              </li>
              <li>
              <a href="{link Menu:add}">Přidat položku</a>
              </li>
            </ul>
            <div class="clear">
            </div>
            </li>
            <li>
            <a href="{link Page:default}">
              <img src="{$baseUri}img/admin/novinky.png" height="50" width="50" alt="Novinky"></a>
            <ul>
              <li>
              <a href="{link Page:}">Články</a>
              </li>
              <li>
              <a href="{link Page:add}">Přidat článek</a>
              </li>
            </ul>
            <div class="clear">
            </div>
            </li>
            <li>
            <a href="{link Foto:}">
              <img src="{$baseUri}img/admin/image_jpeg2000.png" height="50" width="50" alt="Fotografie">            </a>
            <ul>
              <li>
              <a href="{link Foto:}">Fotogalerie</a>
              </li>
              <li>
              <a href="{link Foto:new}">Nová galerie</a>
              </li>
              <li>
              <a href="{link Foto:add}">Přidat foto</a>
              </li>
            </ul>
            <div class="clear">
            </div>
            </li>
            <li>
            <a href="{link Docs:}">
              <img src="{$baseUri}img/admin/kfm.png" height="50" width="50" alt="Dokumenty">  </a>
            <ul>
              <li>
              <a href="{link Docs:}">Dokumenty</a>
              </li>
              <li>
              <a href="{link Docs:add}">Přidat dokument</a>
              </li>
            </ul>
            <div class="clear">
            </div>
            </li>
            <li>
            <a href="{link User:}">
              <img src="{$baseUri}img/admin/preferences_desktop_user.png" height="50" width="50" alt="Uživatele">            </a>
            <ul>
              <li>
              <a href="{link User:}">Uživatele</a>
              </li>
              <li>
              <a href="{link User:add}">Přidat uživatele</a>
              </li>
            </ul>
            <div class="clear">
            </div>
            </li>                     {if isset($user)}
            <li>
            <a href="{link Default:logout}" title="Odhlásit [{? echo implode(', ', $user->roles)}]">
              <img src="{$baseUri}img/admin/user.png" height="50" width="50" alt="Odhlásit {$user->name}"></a>
            <ul>
              <li>
              <a href="{plink Default:}">Odhlásit se</a>
              </li>
            </ul>
            </li>         {/if}
          </ul>
        </div>
      </div>
      <!-- #menu -->
      <div id="dotted">   <h1>{$title|stripTags}</h1>    {foreach $flashes as $flash}
        <div class="flash {$flash->type}">{$flash->message}
        </div>{/foreach}     {include #content}
      </div>
      <!-- #dotted -->
      <div id="paticka">    (c) 2010 David Pavelka. Redakční systém pro správu obsahu Upravuj.
      </div>
      <!-- #footer -->
    </div>
    <!-- #container -->
  </body>
</html>