{block #title}Hlavní panel administrace |{/block} {block #content}   <h1>Hlavní panel administrace</h1>   
<p>Redakční systém Upravuj umožňují kompletní správu obsahu webových stránek. Základní funkcí redakčního systémů je publikování textů a fotografií na web. Systém umožňuje upravovat obsah webů.
</p>  
<div>    
  <div style="float: left; margin-right: 10px;">
    <a href="{plink Default:}">    
      <img src="{$baseUri}img/admin/go_home.png" height="118" width="118" alt="Domů">    
      <br>Seznam pokynů</a>
  </div>    
  <div style="float: left; margin-right: 10px;">
    <a href="{plink Menu:}">    
      <img src="{$baseUri}img/admin/fileview_split.png" height="118" width="118" alt="Menu">    
      <br>Úprava menu</a>
  </div>    
  <div style="float: left; margin-right: 10px;">
    <a href="{plink Page:}">    
      <img src="{$baseUri}img/admin/novinky.png" height="118" width="118" alt="Články">    
      <br>Úprava článků</a>
  </div>    
  <div style="float: left; margin-right: 10px;">
    <a href="{plink User:}">    
      <img src="{$baseUri}img/admin/preferences_desktop_user.png" height="118" width="118" alt="Uživatele">    
      <br>Úprava uživatelů</a>
  </div>    
  <div style="float: left; margin-right: 10px;">
    <a href="{plink Foto:}">    
      <img src="{$baseUri}img/admin/image_jpeg2000.png" height="118" width="118" alt="Fotografie">    
      <br>Správa fotografií</a>
  </div>    
  <div style="float: left; margin-right: 10px;">
    <a href="{plink Docs:}">    
      <img src="{$baseUri}img/admin/kfm.png" height="118" width="118" alt="Dokumenty">    
      <br>Správa dokumentů</a>
  </div>    
  <div style="float: left; margin-right: 10px;">
    <a href="napoveda.pdf">    
      <img src="{$baseUri}img/admin/help_hint.png" height="118" width="118" alt="Uživatele">    
      <br>Nápověda systému</a>
  </div>  
</div>


<hr class="cistic">{/block}
