{block #title}{foreach $menu_id as $_menu}{$_menu->nazev}{/foreach}{include #parent}{/block} {block #content}   {foreach $menu_id as $_menu}   <h1>{$_menu->nazev}</h1>  	{!$_menu->obsah} {/foreach}             {foreach $foto as $_foto}      
<p>Fotogalerie: <i>
    <a href="{link foto, $_foto->id, $_foto->nazev_slozky}">{$_foto->titulek}</i></a>
</p>     {/foreach}           {foreach $stranky as $_stranky}   
<p>
  <a href="{link clanky, $_stranky->id, $_stranky->url}">{$_stranky->titulek} </a>
  <br>  {$_stranky->text_uvodni_strana})
</p>{/foreach} {foreach $docs as $_docs}   
<p>  
  <img src="{$basePath}/img/web/{$_docs->typ_souboru}.jpg">   {$_docs->titulek}    (vyvěšeno {$_docs->vyveseno_od})
  <br>  
  <a href="{$basePath}/docs/{$_docs->nazev_souboru}.{$_docs->typ_souboru}">(soubor ve formátu .{$_docs->typ_souboru})</a>
</p>{/foreach}